In [1]:
x = """What is Amazon Comprehend. A natural-language processing (NLP) service that uses machine learning to uncover valuable insights and connections in text.
 Uncover valuable insights from text in documents, customer support tickets, product reviews, emails, social media feeds, and more."""

# Word Tokenization

In [2]:
from nltk.tokenize import word_tokenize
w = word_tokenize(x)
#w

# Sentence Tokenization

In [3]:
from nltk.tokenize import sent_tokenize
s = sent_tokenize(x)
#s

# Punctuation

In [4]:
from nltk import pos_tag
p = pos_tag(w)
#p

# Stop words

In [5]:
from nltk.corpus import stopwords
stop_words = stopwords.words("english")
#stop_words

In [6]:
from string import punctuation
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [7]:
all_stop_word = list(punctuation) + stop_words

for i in w:
    if i not in all_stop_word:
        #print(i)
        #print(type(i))
        pass

# Stemerization

In [8]:
from nltk.stem import LancasterStemmer, RegexpStemmer, PorterStemmer, SnowballStemmer
l = LancasterStemmer()
r = RegexpStemmer('ing')
p = PorterStemmer()
s = SnowballStemmer('english')

In [9]:
print(l.stem("changing"),  r.stem("changing"),  p.stem("changing"),  s.stem("changing"))

chang chang chang chang

# Lammatization

In [10]:
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()
wl.lemmatize("mice")

'mouse'

# n-grams

In [11]:
from nltk.collocations import BigramCollocationFinder, TrigramCollocationFinder, ngrams
b = BigramCollocationFinder.from_words(w)
t = TrigramCollocationFinder.from_words(w)
n = ngrams(w, 2)
#b.ngram_fd
#t.ngram_fd
#for i in n:
    #print(i)

# Vectorizer

In [12]:
l = ["my name is khushi agrawal", "i am doing nlp demonstration"]
import pandas as pd
df = pd.DataFrame({"data" : l})
df

                           data
0     my name is khushi agrawal
1  i am doing nlp demonstration

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
new_data = cv.fit_transform(df["data"]).toarray()
new_data

array([[1, 0, 0, 0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 1]])

In [14]:
cv.vocabulary_

{'my': 6,
 'name': 7,
 'is': 4,
 'khushi': 5,
 'agrawal': 0,
 'am': 1,
 'doing': 3,
 'nlp': 8,
 'demonstration': 2}

# Word Sense Disambiguation

In [15]:
w = "machine learning"
from nltk.wsd import lesk
l = lesk(word_tokenize(w), "Machine")

# NLP on Spam Dateset

In [16]:
import re
import nltk

In [17]:
df = pd.read_csv(r"C:\Users\agraw\OneDrive\Desktop\spam.csv", encoding="latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [19]:
df.describe()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
count,5572,5572,50,12,6
unique,2,5169,43,10,5
top,ham,"Sorry, I'll call later","bt not his girlfrnd... G o o d n i g h t . . .@""","MK17 92H. 450Ppw 16""","GNT:-)"""
freq,4825,30,3,2,2

In [20]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [21]:
df = df[["v1", "v2"]]
df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [22]:
df.rename(columns={"v1": "label", "v2": "message"}, inplace=True)
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [23]:
df.duplicated().sum()

np.int64(403)

In [24]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [25]:
df["label"].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

In [26]:
df["message"] = df["message"].str.lower()
df["message"].head()

0    go until jurong point, crazy.. available only ...
1                        ok lar... joking wif u oni...
2    free entry in 2 a wkly comp to win fa cup fina...
3    u dun say so early hor... u c already then say...
4    nah i don't think he goes to usf, he lives aro...
Name: message, dtype: object

In [27]:
df["length"] = df["message"].apply(len)
df.head()

  label                                            message  length
0   ham  go until jurong point, crazy.. available only ...     111
1   ham                      ok lar... joking wif u oni...      29
2  spam  free entry in 2 a wkly comp to win fa cup fina...     155
3   ham  u dun say so early hor... u c already then say...      49
4   ham  nah i don't think he goes to usf, he lives aro...      61

In [28]:
# word tokenisation, stopwords, stemmerization
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [29]:
# word tokenisation
w = word_tokenize(x)

In [30]:
# listing of stopwords
stop_words = stopwords.words("english")

In [31]:
# Remove stopwords
df["message"] = df["message"].apply(
    lambda x: " ".join(
        [word for word in w if word not in stop_words]))

In [32]:
# Stemming
p = PorterStemmer()

In [33]:
df["message"] = df["message"].apply(
    lambda x: " ".join(
        [p.stem(word) for word in x.split()]))

In [34]:
X = df["message"]
Y = df["label"]

In [35]:
# TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

t = TfidfVectorizer(max_features=3000)
X_vec = t.fit_transform(X)

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_vec,Y,test_size=0.20, random_state=42)

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, Y_train)

MultinomialNB()

In [38]:
from sklearn.metrics import accuracy_score, classification_report

Y_pred = model.predict(X_test)

print(accuracy_score(Y_test, Y_pred), classification_report(Y_test, Y_pred))

0.8597678916827853               precision    recall  f1-score   support

         ham       0.86      1.00      0.92       889
        spam       0.00      0.00      0.00       145

    accuracy                           0.86      1034
   macro avg       0.43      0.50      0.46      1034
weighted avg       0.74      0.86      0.79      1034

C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [39]:
sample_message = ["free entry win cash prize now"]
sample = t.transform(sample_message)

prediction = model.predict(sample)

print(prediction[0])

ham