In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = pd.DataFrame({"name" : ["a", "b", "c", "d"]})
df

  name
0    a
1    b
2    c
3    d

In [2]:
le.fit(df)

C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LabelEncoder()

In [3]:
le.transform(df)

C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0, 1, 2, 3])

In [4]:
df["e_name"] = le.fit_transform(df)

C:\Users\agraw\Downloads\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [5]:
df.drop(columns = "name", inplace = True)

In [6]:
df

   e_name
0       0
1       1
2       2
3       3

In [7]:
ds = pd.read_csv(r"C:\Users\agraw\OneDrive\Desktop\loan dataset.zip")
ds.head(10)

,loan_id,gender,married,dependents,education,self_employed,applicantincome,coapplicantincome,loanamount,loan_amount_term,credit_history,property_area,loan_status
0,lp001002,male,no,0,graduate,no,5849,0.0,NaN,360.0,1.0,urban,y
1,lp001003,male,yes,1,graduate,no,4583,1508.0,128.0,360.0,1.0,rural,n
2,lp001005,male,yes,0,graduate,yes,3000,0.0,66.0,360.0,1.0,urban,y
3,lp001006,male,yes,0,not graduate,no,2583,2358.0,120.0,360.0,1.0,urban,y
4,lp001008,male,no,0,graduate,no,6000,0.0,141.0,360.0,1.0,urban,y
5,lp001011,male,yes,2,graduate,yes,5417,4196.0,267.0,360.0,1.0,urban,y
6,lp001013,male,yes,0,not graduate,no,2333,1516.0,95.0,360.0,1.0,urban,y
7,lp001014,male,yes,3+,graduate,no,3036,2504.0,158.0,360.0,0.0,semiurban,n
8,lp001018,male,yes,2,graduate,no,4006,1526.0,168.0,360.0,1.0,urban,y
9,lp001020,male,yes,1,graduate,no,12841,10968.0,349.0,360.0,1.0,semiurban,n

In [8]:
ds["property_area"].unique()

array(['urban', 'rural', 'semiurban'], dtype=object)

In [9]:
ds["property_area"] = le.fit_transform(ds["property_area"])

In [10]:
ds.head(10)

,loan_id,gender,married,dependents,education,self_employed,applicantincome,coapplicantincome,loanamount,loan_amount_term,credit_history,property_area,loan_status
0,lp001002,male,no,0,graduate,no,5849,0.0,NaN,360.0,1.0,2,y
1,lp001003,male,yes,1,graduate,no,4583,1508.0,128.0,360.0,1.0,0,n
2,lp001005,male,yes,0,graduate,yes,3000,0.0,66.0,360.0,1.0,2,y
3,lp001006,male,yes,0,not graduate,no,2583,2358.0,120.0,360.0,1.0,2,y
4,lp001008,male,no,0,graduate,no,6000,0.0,141.0,360.0,1.0,2,y
5,lp001011,male,yes,2,graduate,yes,5417,4196.0,267.0,360.0,1.0,2,y
6,lp001013,male,yes,0,not graduate,no,2333,1516.0,95.0,360.0,1.0,2,y
7,lp001014,male,yes,3+,graduate,no,3036,2504.0,158.0,360.0,0.0,1,n
8,lp001018,male,yes,2,graduate,no,4006,1526.0,168.0,360.0,1.0,2,y
9,lp001020,male,yes,1,graduate,no,12841,10968.0,349.0,360.0,1.0,1,n

In [11]:
ds["education"] = ds["education"].map({"not_graduate" : 0, "graduate" : 1, "NaN" : 2})

In [12]:
ds["property_area"].unique()

array([2, 0, 1])

In [13]:
ds.head()

,loan_id,gender,married,dependents,education,self_employed,applicantincome,coapplicantincome,loanamount,loan_amount_term,credit_history,property_area,loan_status
0,lp001002,male,no,0,1.0,no,5849,0.0,NaN,360.0,1.0,2,y
1,lp001003,male,yes,1,1.0,no,4583,1508.0,128.0,360.0,1.0,0,n
2,lp001005,male,yes,0,1.0,yes,3000,0.0,66.0,360.0,1.0,2,y
3,lp001006,male,yes,0,NaN,no,2583,2358.0,120.0,360.0,1.0,2,y
4,lp001008,male,no,0,1.0,no,6000,0.0,141.0,360.0,1.0,2,y

In [14]:
ds = pd.DataFrame({"size" : ["s","m","l","m","xl","s","l","xl"]})
ds

  size
0    s
1    m
2    l
3    m
4   xl
5    s
6    l
7   xl

In [15]:
data = [["s","m","l","xl"]]
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = data)

In [16]:
 oe.fit_transform(ds[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [3.],
       [0.],
       [2.],
       [3.]])

In [17]:
ds["size"] =  oe.fit_transform(ds[["size"]])
ds

   size
0   0.0
1   1.0
2   2.0
3   1.0
4   3.0
5   0.0
6   2.0
7   3.0

In [18]:
data1 = {"s" : 0, "m" : 1, "l" : 2, "xl" : 3}
df = pd.DataFrame({"size" : ["xl", "m", "s", "l", "s", "xl"]})
df["size"].map(data1)

0    3
1    1
2    0
3    2
4    0
5    3
Name: size, dtype: int64